/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Booking/booking`; params?: Router.UnknownInputParams; } | { pathname: `/ButtonNav/components`; params?: Router.UnknownInputParams; } | { pathname: `/Department/department`; params?: Router.UnknownInputParams; } | { pathname: `/Department/departmentDoctors`; params?: Router.UnknownInputParams; } | { pathname: `/Doctor/appoinment`; params?: Router.UnknownInputParams; } | { pathname: `/Doctor/booking`; params?: Router.UnknownInputParams; } | { pathname: `/Doctor/doctorHome`; params?: Router.UnknownInputParams; } | { pathname: `/Doctor/editDoctor`; params?: Router.UnknownInputParams; } | { pathname: `/DoctorBottomNav/doctorComponents`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/aiChat` | `/Home/aiChat`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/doctorDetails` | `/Home/doctorDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/home` | `/Home/home`; params?: Router.UnknownInputParams; } | { pathname: `/Hospital/hospitalDoctors`; params?: Router.UnknownInputParams; } | { pathname: `/Hospital/hospitals`; params?: Router.UnknownInputParams; } | { pathname: `/screen/first`; params?: Router.UnknownInputParams; } | { pathname: `/screen/login`; params?: Router.UnknownInputParams; } | { pathname: `/screen/signup`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Booking/booking`; params?: Router.UnknownOutputParams; } | { pathname: `/ButtonNav/components`; params?: Router.UnknownOutputParams; } | { pathname: `/Department/department`; params?: Router.UnknownOutputParams; } | { pathname: `/Department/departmentDoctors`; params?: Router.UnknownOutputParams; } | { pathname: `/Doctor/appoinment`; params?: Router.UnknownOutputParams; } | { pathname: `/Doctor/booking`; params?: Router.UnknownOutputParams; } | { pathname: `/Doctor/doctorHome`; params?: Router.UnknownOutputParams; } | { pathname: `/Doctor/editDoctor`; params?: Router.UnknownOutputParams; } | { pathname: `/DoctorBottomNav/doctorComponents`; params?: Router.UnknownOutputParams; } | { pathname: `/Home${'/(tabs)'}/aiChat` | `/Home/aiChat`; params?: Router.UnknownOutputParams; } | { pathname: `/Home${'/(tabs)'}/doctorDetails` | `/Home/doctorDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/Home${'/(tabs)'}/home` | `/Home/home`; params?: Router.UnknownOutputParams; } | { pathname: `/Hospital/hospitalDoctors`; params?: Router.UnknownOutputParams; } | { pathname: `/Hospital/hospitals`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/first`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/login`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/signup`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Booking/booking${`?${string}` | `#${string}` | ''}` | `/ButtonNav/components${`?${string}` | `#${string}` | ''}` | `/Department/department${`?${string}` | `#${string}` | ''}` | `/Department/departmentDoctors${`?${string}` | `#${string}` | ''}` | `/Doctor/appoinment${`?${string}` | `#${string}` | ''}` | `/Doctor/booking${`?${string}` | `#${string}` | ''}` | `/Doctor/doctorHome${`?${string}` | `#${string}` | ''}` | `/Doctor/editDoctor${`?${string}` | `#${string}` | ''}` | `/DoctorBottomNav/doctorComponents${`?${string}` | `#${string}` | ''}` | `/Home${'/(tabs)'}/aiChat${`?${string}` | `#${string}` | ''}` | `/Home/aiChat${`?${string}` | `#${string}` | ''}` | `/Home${'/(tabs)'}/doctorDetails${`?${string}` | `#${string}` | ''}` | `/Home/doctorDetails${`?${string}` | `#${string}` | ''}` | `/Home${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/Home/home${`?${string}` | `#${string}` | ''}` | `/Hospital/hospitalDoctors${`?${string}` | `#${string}` | ''}` | `/Hospital/hospitals${`?${string}` | `#${string}` | ''}` | `/screen/first${`?${string}` | `#${string}` | ''}` | `/screen/login${`?${string}` | `#${string}` | ''}` | `/screen/signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Booking/booking`; params?: Router.UnknownInputParams; } | { pathname: `/ButtonNav/components`; params?: Router.UnknownInputParams; } | { pathname: `/Department/department`; params?: Router.UnknownInputParams; } | { pathname: `/Department/departmentDoctors`; params?: Router.UnknownInputParams; } | { pathname: `/Doctor/appoinment`; params?: Router.UnknownInputParams; } | { pathname: `/Doctor/booking`; params?: Router.UnknownInputParams; } | { pathname: `/Doctor/doctorHome`; params?: Router.UnknownInputParams; } | { pathname: `/Doctor/editDoctor`; params?: Router.UnknownInputParams; } | { pathname: `/DoctorBottomNav/doctorComponents`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/aiChat` | `/Home/aiChat`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/doctorDetails` | `/Home/doctorDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/home` | `/Home/home`; params?: Router.UnknownInputParams; } | { pathname: `/Hospital/hospitalDoctors`; params?: Router.UnknownInputParams; } | { pathname: `/Hospital/hospitals`; params?: Router.UnknownInputParams; } | { pathname: `/screen/first`; params?: Router.UnknownInputParams; } | { pathname: `/screen/login`; params?: Router.UnknownInputParams; } | { pathname: `/screen/signup`; params?: Router.UnknownInputParams; };
    }
  }
}
